version: "2"
services:
  user_service:
    container_name: user_service
    build: ./
    restart: always
    ports:
      - "3002:3000"
    command: npm run dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - budget_app_network
networks:
  budget_app_network:
    external: true
